In [ ]:
import numpy as np
from sklearn.preprocessing import normalize

In [ ]:
train = np.load("../data/train_text_embs_user2_small_384dim.npy")
test = np.load("../data/test_text_embs_user2_small_384dim.npy")

In [ ]:
train.shape, test.shape

((197198, 384), (22760, 384))

In [ ]:
np.linalg.norm(train[::100][:5], axis=1)

array([2.077808 , 2.6245546, 5.1355867, 2.903278 , 2.9690819],
      dtype=float32)

In [ ]:
np.linalg.norm(test[::100][:5], axis=1)

array([3.390613 , 4.585647 , 5.319827 , 3.1218576, 3.2516918],
      dtype=float32)

In [ ]:
train_norm = normalize(train, axis=1)
test_norm = normalize(test, axis=1)

In [ ]:
train_norm.shape, test_norm.shape

((197198, 384), (22760, 384))

In [ ]:
np.linalg.norm(train_norm[::100][:5], axis=1)

array([0.99999994, 0.99999994, 0.99999994, 1.        , 1.        ],
      dtype=float32)

In [ ]:
np.linalg.norm(test_norm[::100][:5], axis=1)

array([1.0000001 , 1.0000001 , 0.99999994, 1.        , 1.        ],
      dtype=float32)

In [ ]:
np.save("../data/train_text_embs_norm_user2_small_384dim.npy", train_norm)
np.save("../data/test_text_embs_norm_user2_small_384dim.npy", test_norm)