In [ ]:
import numpy as np
import pandas as pd

In [ ]:
qwe = pd.read_csv("../data/1__test_with_flags.csv")
qwe.shape

(22760, 47)

In [12]:
qwe.loc[[1, 2, 3, 8], ["has_image", "has_brand_name"]]

has_image  has_brand_name
1          1               1
2          1               1
3          1               1
8          1               1

In [ ]:
qwe.loc[[1], ["has_image", "has_brand_name"]].to_numpy().squeeze()

array([1, 1])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
qwe.iloc[22759]

id                                                                            371
brand_name                                                                  Dyson
description                     Европейская вилка! Переходник не требуется.Обн...
name_rus                        Стайлер Dyson Airwrap Complete Long Volumise H...
CommercialTypeName4                                Стайлер, щипцы для волос Dyson
rating_1_count                                                                NaN
rating_2_count                                                                NaN
rating_3_count                                                                NaN
rating_4_count                                                                NaN
rating_5_count                                                                NaN
comments_published_count                                                      NaN
photos_published_count                                                        NaN
videos_published

In [ ]:
img_embs = np.load("../data/test_text_embs_user2_small_384dim.npy")
img_embs.shape

(22760, 384)

In [ ]:
np.linalg.norm(img_embs, axis=1)

array([3.390613 , 2.227669 , 2.9934115, ..., 2.654228 , 3.3956816,
       3.1042452], shape=(22760,), dtype=float32)